mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostFeed

app_name = "blog"

urlpatterns = [
    #path("", views.PostListView.as_view(), name="post_list"),
    path("", views.post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/',
         views.post_detail,
         name='post_detail'),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("feed/", LatestPostFeed(), name="post_feed"),
    path("search/", views.search_post, name="post_search"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSiteMap

sitemaps = {
    "posts":PostSiteMap
}

urlpatterns = [
    path("", include("blog.urls")),
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
         "sitemap.xml", sitemap,
         {"sitemaps":sitemaps},
         name="django.contrib.sitemaps.views.sitemap"
    )
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

# CUSTOME MODEL MANAGER
class PublishManager(models.Manager):
    """ 
        Define a custome manager that
        retrieves objs with status set to published
    """
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    """ Post model map to table in a db """
    
    objects = models.Manager()
    published = PublishManager()
    tags = TaggableManager()

    class Status(models.TextChoices):
        """ Use to define the status or state of a blog post """
        DRAFT = "DF", "DRAFT"
        PUBLISHED = "PB", "PUBLISHED"


    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=100, choices=Status.choices, default=Status.DRAFT)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")

    # DEFINE METADATA FOR OUR MODEL
    class Metal:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"])
        ]
    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('blog:post_detail', 
                       args=[
                           self.publish.year,
                           self.publish.month,
                           self.publish.day,
                           self.slug
                        ])

# COMMENT MODEL
class Comment(models.Model):
    """ Defines comment table structure """
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name="comments")
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    # META PROPS
    class Meta:
        """ Adds meta props to model """
        ordering = ["created_at"]
        indexes = [models.Index(fields=["created_at"])]
    def __str__(self):
        """ Handle string reprs of object """
        return f"Commented by {self.name} on {self.post}"

mysite/blog/forms.py
"""
    Defines forms used by the blog app
"""
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    """ Define the email form structure """
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)
    
# COMMENT FORM
class CommentForm(forms.ModelForm):
    """ Build a form from an existing model """
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]

# SEARCH FORM
class SearchForm(forms.Form):
    """ provide post searching capabilities """
    query = forms.CharField(max_length=100)

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse
from .models import Post, Comment
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity

# FUNCTIONAL BASE VIEWS HERE
def post_list(request, tag_slug=None):
    """ Display all posts """
    
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Pagination
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get("page", 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        "posts":posts,
        "tag":tag,
    }
    return render(request, "blog/post/list.html", context)
    
def post_detail(request, year, month, day, slug):
    """ Display Post Each Post Details """

    # try:
    #     post = Post.published.get(
    #        publish__year = year,
    #        publish__month = month,
    #        publish__day = day,
    #        slug = post
    #     )
    #    
    # except Post.DoesNotExist:
    #     raise Http404("No Post Found")

    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=slug
    )
    comments = post.comments.filter(active=True)
    post_tags_id = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_id)\
                                       .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tag=Count("tags"))\
                                         .order_by("-same_tag", "-publish")[:4]
    form = CommentForm()
    context = {"post":post, "comments":comments, "form":form, "similar_posts":similar_posts}
    return render(request, "blog/post/detail.html", context)

def post_share(request, post_id):
    """ Handle displaying of form, form submmison and emailing """
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, id=post_id)
    sent = False
    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            # Send mail
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject=subject, message=message, from_email="admin@admin.com", recipient_list=["iyktech09@gmail.com"])
            sent = True
    else:
        form = EmailPostForm()
    context = {
        "post":post,
        "form":form,
        "sent":sent
    }
    return render(request, "blog/post/share.html", context)

@require_POST
def post_comment(request, post_id):
    """ Handle comment submmisions """
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
       "post":post,
       "form":form,
       "comment":comment
    }
    return render(request, "blog/post/comment.html", context)
    
# SEARCH FEATURE
def search_post(request):
    """ Handle search for post """
    query = None
    results = []
    form = SearchForm(request.GET)
    if "query" in request.GET:
        if form.is_valid():
            query = form.cleaned_data["query"]
            search_query = SearchQuery(query)
            search_vector = SearchVector("title", weight="A") + SearchVector("body", weight="B")
            results = Post.published.annotate(
                similarity=TrigramSimilarity("title", query),
            ).filter(similarity__gt=0.1).order_by("-similarity")
        
    context = {
        "form":form,
        "query":query,
        "results":results
    }
    return render(request, "blog/post/search.html", context)
#----------------------------------------------------------------#

# CLASS BASE VIEWS HERE
class PostListView(ListView):
    """ Class base view for handling display of all posts """
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3
    template_name = "blog/post/list.html"

mysite/blog/templates/blog/post/comment.html
{% extends "../base.html" %}
{% block title %} Add Comment {% endblock %}
{% block content %}
   {% if comment %}
      <h2> Your comment has been added </h2>
      <a href="{{ post.get_absolute_url }}">
          Back to the post
      </a>
   {% else %}
      {% include "./includes/comment_form.html" %}
   {% endif %}
{% endblock %}
     

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
   <h1>{{ post.title }}</h1>
   <pclass="date">
   Published {{ post.publish }} by {{ post.author }}
   <ul>
      <li>{{ post.publish.year }}</li>
      <li>{{ post.publish.month }}</li>
      <li>{{ post.publish.day }}</li>
   </ul>
   </p>
   {{ post.body|markdown|linebreaks }}
   <p>
      <a href="{% url 'blog:post_share' post.id %}">
         Share Post
      </a>
   </p>
   <h2> Similar posts </h2>
   {% for post in similar_posts %}
       <p class="similar_post">
           <a href="{{ post.get_absolute_url }}">
               {{ post.title }}
           </a>
       </p>
   {% empty %}
       <p>
           No similar posts
       </p>
   {% endfor %}
   {% with comments.count as total_comment %}
      <h2>
         {{ total_comment }} comment {{ total_comments|pluralize }}
      </h2>
   {% endwith %}
   {% for comment in comments %}
      <div class="comment">
         <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created_at }}
         </p>
         {{ comment.body|linebreaks  }}
      </div>
   {% empty %}
      <p> There are no comment </p>
   {% endfor %}
   {% include "./includes/comment_form.html" %}
{% endblock %}

mysite/blog/templates/blog/post/latest.html
<ul class="latest">
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
         </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>
            Posts tagged with {{ tag.name }}
        </h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <h3 class="tags">
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %} ,{% endif %}
            {% endfor %}
        </h3>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30|linebreaks }} 
    {% endfor %}
    {% include "./pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">
                Previous
            </a>
        {% endif %}
        <span class="current">
             Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">
                Next
            </a>
        {% endif %}
    </span>
</div>

mysite/blog/templates/blog/post/search.html
{% extends "../base.html" %}
{% load blog_tags %}
{% block title %} Search Blog {% endblock %}
{% block content %}
    {% if query %}
        <h2> Post containing {{ query }} </h2>
        <h3>
            {% with results.count as total_results %}
                Found {{total_results}} Result{{ total_results|pluralize}}
            {% endwith %}
        </h3>
        {% for post in results %}
            <a href="{{post.get_absolute_url}}">{{ post.title }}</a>
            <p>
                {{post.body|markdown|truncatewords_html:12}}
            </p>
        {% empty %}
            <p>
                There are no results for your query.
            </p>
        {% endfor %}
        <a href="{% url 'blog:post_search' %}">Search</a>
    {% else %}
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form> 
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "../base.html" %}
{% block title %} Share Post {% endblock %}
{% block content %}
    {% if sent %}
        <h2> E-mail sent successfully </h2>
        <p>
            {{ post.title }} was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1> Share {{ post.title }} by email </h1>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send email"/>
        </form>
    {% endif %}
{% endblock %}